In [2]:
import numpy as np

In [3]:
a_array = np.array([0,1,2,3,4,5])
a_array

array([0, 1, 2, 3, 4, 5])

In [5]:
a_array.dtype

dtype('int64')

In [6]:
flt_array = np.array([1,2,3,4,5],dtype=np.float64)
flt_array

array([1., 2., 3., 4., 5.])

In [7]:
flt_array.ndim, flt_array.shape, flt_array.size

(1, (5,), 5)

In [8]:
b = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float64)
b

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [9]:
b.ndim, b.shape, b.size

(2, (2, 4), 8)

In [22]:
a = np.zeros((5,5),'d')
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
b = np.empty((3,3),'d')
b

array([[2.31584178e+077, 1.29073679e-231, 6.05202892e-066],
       [2.12978418e-052, 5.02633325e-037, 1.41529403e+161],
       [6.00736899e-067, 5.16656600e+097, 1.29073679e-231]])

In [30]:
np.linspace(0,10,5) # 5 numbers within 0 to 10 with equal difference

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.arange(0,10,2) # numbers within 0 to 10 with step size 2

array([0, 2, 4, 6, 8])

In [33]:
np.random.standard_normal((2,4))

array([[-0.8780824 , -0.04025891,  0.96350324, -0.68857609],
       [-0.03573485, -0.53991069,  0.92332315, -1.71677458]])

In [34]:
a = np.random.standard_normal((2,3))
a

array([[ 1.52295484, -1.14557134, -1.04183571],
       [ 0.54199042,  0.61611762, -2.18302736]])

In [35]:
b = np.random.standard_normal((2,3))
b

array([[ 1.29613447,  0.91008464,  0.91442477],
       [ 1.27908535, -0.14046519,  1.03836955]])

In [36]:
np.vstack([a,b]) # Vertical stacking 2 arrays

array([[ 1.52295484, -1.14557134, -1.04183571],
       [ 0.54199042,  0.61611762, -2.18302736],
       [ 1.29613447,  0.91008464,  0.91442477],
       [ 1.27908535, -0.14046519,  1.03836955]])

In [37]:
np.hstack([a,b]) # Horizontal append

array([[ 1.52295484, -1.14557134, -1.04183571,  1.29613447,  0.91008464,
         0.91442477],
       [ 0.54199042,  0.61611762, -2.18302736,  1.27908535, -0.14046519,
         1.03836955]])

In [39]:
np.transpose(a) # m cross n matrix converted to n cross m

array([[ 1.52295484,  0.54199042],
       [-1.14557134,  0.61611762],
       [-1.04183571, -2.18302736]])

In [40]:
np.save('example.npy',a)

In [41]:
c = np.load('example.npy')

In [42]:
c

array([[ 1.52295484, -1.14557134, -1.04183571],
       [ 0.54199042,  0.61611762, -2.18302736]])